# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60e87710a84470a69676dc066852d0ed9a0545e2c4a214bbdba81e947327ae7c2e9a4641377e065bd0d02fb1dc8369b4b3b1e03d1520b3c3928c14869b79a2a0

test:
  secret_key_base: ea4cabd1ef820e0941b7a16cea02fa17e752a68beecb915af397cd969a4a700c62c8598c51a40c8c9fe5e91e2142171505405fc42946293f7af77a259e5e3051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
